spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/socks
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: PassworD1

    extra_hosts:
      - "host.docker.internal:host-gateway"